# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://brainbicycle.net
title: Brain Bicycle
subtitle:
author: Mike Bannister
simple_search: http://google.com/search

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10
pagination_dir: blog
recent_posts: 5
excerpt_link: "More &rarr;"

default_asides: [asides/links.html, asides/twitter.html, asides/github.html, asides/recent_posts.html]

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Twitter
twitter_user: possibilities
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Github repositories
github_user: mikebannister
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Google Plus
google_plus_one: true
google_plus_one_size: medium

# Disqus Comments
disqus_short_name: brainbicycle
disqus_show_comment_count: 5

# Google Analytics
google_analytics_tracking_id: UA-4126287-5
